SELECT [SalesPersonID]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[CustomerID]
      ,[CurrentSalesPersonFrequency]
      ,[CurrentSalesPersonFrequencyScore]
  FROM [test].[dbo].[DimSalesPerson]
