SELECT [FactID]
      ,[DateID]
      ,[CustomerID]
      ,[SalesOrderID]
      ,[SalesPersonID]
      ,[SubTotal]
      ,[Tax]
      ,[Freight]
      ,[TotalDue]
      ,[TotalSpent]
      ,[SalesPersonFrequency]
      ,[SalesPersonFrequencyScore]
      ,[TotalSpentScore]
      ,[TotalFrequency]
      ,[TotalFrequencyScore]
      ,[Recency]
      ,[RecencyScore]
      ,[ChurnRatio]
      ,[ChurnScore]
  FROM [test].[dbo].[FactCustomerChurn]
  ORDER BY FactID DESC;
